version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: "on-failure"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: "on-fauilure"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  client:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: client
    restart: "on-failure"
    ports:
      - 3000:3000
    volumes:
      - './:/usr/src/app'
      - '/app/node_modules'
    environment: 
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true